import Sidebar from "./_components/Sidebar";

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function LaytoutAdmin({ children }) {
  return (
    <>
        <Sidebar id={'scroll'}> 
          {children}
        </Sidebar>
      
    </>
  );
}