import { Toaster } from "react-hot-toast";
import { Footer } from "./_components/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center"/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
